# Generated by Django 3.1.4 on 2020-12-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='main_room', max_length=20, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('guest_conrtol', models.BooleanField(default=False)),
                ('skip_votes', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
